import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Animotion <a href="https://popmotion.io/">js 👋</a>
				</h1>

				<p className={styles.description}>Comencemos</p>

				<div className={styles.grid}>
					<a href="https://nextjs.org/docs" className={styles.card}>
						<h2>1</h2>
					</a>

					<a href="" className={styles.card}>
						<h2>2</h2>
					</a>

					<a href="" className={styles.card}>
						<h2>3</h2>
					</a>

					<a href="" className={styles.card}>
						<h2>4</h2>
					</a>
				</div>
			</main>
		</div>
	);
}
